# This is a boilerplate parameters config generated for pipeline 'yolo_v8_base'
# using Kedro 0.19.9.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.19.9/configuration/parameters.html

yolo_v8_fine_tune:
  model_name: yolov8n-seg.pt
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  random_state: 42
  # Added training parameters
  epochs: 100
  imgsz: 640
  batch_size: 16
  device: cpu
  save_period: -1
  patience: 50
  project: yolo_training
  run_name: exp
  num_classes: 1
  class_names: ["bead"]
